version: '3.8'

services:
  db:
    image: mysql:5.7.33
    container_name: myforest_db
    ports:
      - 3306:3306
    volumes: 
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env.db
    networks:
      - myforest_network

  app:
    container_name: myforest_app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    depends_on:
      - db
    ports:
      - 80:80
    command:
      - bash
      - -c
      - |
        /app/wait-for-it.sh db:3306 -t 20
        npm run start
    volumes:
      - ./:/app/
    networks:
      - myforest_network

networks:
  myforest_network:
